version: 2

sources:
  - name: erp
    description: fonte sap vendas northwind
    schema: erp_northwind
    tables:
    - name: categories
      columns: 
        - name: category_id
          tests:
            - unique
            - not_null


    - name: suppliers


    - name: products

  
    - name: employees


    - name: orders
      description: uma linha por pedido (nf). inclui pedidos canc e del
      columns:
        - name: order_id
          tests:
            - unique
            - not_null
              

    - name: order_details


    - name: customers